nodes:
- name: "ns50"
  uuid: "a5822889-cf81-4db6-b5ae-8180dc90e9b6"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
  - id: 1
    cores:
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 12
    - id: 13
    - id: 14
    - id: 15
- name: "ns51"
  uuid: "506c38e1-cdd7-4bfc-b9c9-18a21caf16f8"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
  - id: 1
    cores:
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 12
    - id: 13
    - id: 14
    - id: 15
- name: "ns54"
  uuid: "69032188-ac59-4896-adc6-806346b0d1a5"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns55"
  uuid: "c34c2ecb-6291-4bf2-b018-1435e3e9534b"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns56"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns57"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns58"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns59"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns60"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns61"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns62"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns63"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 30720
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 32
    - id: 33
    - id: 34
    - id: 35
  - id: 1
    cores:
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
- name: "ns64"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 20480
  sockets:
  - id: 0
      cores:
      - id: 0
      - id: 1
      - id: 2
      - id: 3
      - id: 4
      - id: 5
      - id: 6
      - id: 7
      - id: 16
      - id: 17
      - id: 18
      - id: 19
      - id: 20
      - id: 21
      - id: 22
      - id: 23
  - id: 1
      cores:
      - id: 8
      - id: 9
      - id: 10
      - id: 11
      - id: 12
      - id: 13
      - id: 14
      - id: 15
      - id: 24
      - id: 25
      - id: 26
      - id: 27
      - id: 28
      - id: 29
      - id: 30
      - id: 31
- name: "ns65"
  threadsPerCore: 2
  maxGHz: 2.6 
  l1dCache: 32
  l1iCache: 32
  l2Cache: 256
  l3Cache: 20480
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
  - id: 1
    cores:
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
- name: "ns66"
  threadsPerCore: 2
  maxGHz: 2.0
  l1dCache: 32
  l1iCache: 32
  l2Cache: 1024
  l3Cache: 22528
  sockets:
  - id: 0
    cores:
    - id: 0
    - id: 1
    - id: 2
    - id: 3
    - id: 4
    - id: 5
    - id: 6
    - id: 7
    - id: 8
    - id: 9
    - id: 10
    - id: 11
    - id: 12
    - id: 13
    - id: 14
    - id: 15
    - id: 32
    - id: 33
    - id: 34
    - id: 35
    - id: 36
    - id: 37
    - id: 38
    - id: 39
    - id: 40
    - id: 41
    - id: 42
    - id: 43
    - id: 44
    - id: 45
    - id: 46
    - id: 47
  - id: 1
    cores:
    - id: 16
    - id: 17
    - id: 18
    - id: 19
    - id: 20
    - id: 21
    - id: 22
    - id: 23
    - id: 24
    - id: 25
    - id: 26
    - id: 27
    - id: 28
    - id: 29
    - id: 30
    - id: 31
    - id: 48
    - id: 49
    - id: 50
    - id: 51
    - id: 52
    - id: 53
    - id: 54
    - id: 55
    - id: 56
    - id: 57
    - id: 58
    - id: 59
    - id: 60
    - id: 61
    - id: 62
    - id: 63